// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: ticker.proto

package ticker

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TickerService_StreamTicker_FullMethodName = "/ticker.TickerService/StreamTicker"
)

// TickerServiceClient is the client API for TickerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TickerServiceClient interface {
	StreamTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickerUpdate], error)
}

type tickerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTickerServiceClient(cc grpc.ClientConnInterface) TickerServiceClient {
	return &tickerServiceClient{cc}
}

func (c *tickerServiceClient) StreamTicker(ctx context.Context, in *TickerRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TickerUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TickerService_ServiceDesc.Streams[0], TickerService_StreamTicker_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TickerRequest, TickerUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TickerService_StreamTickerClient = grpc.ServerStreamingClient[TickerUpdate]

// TickerServiceServer is the server API for TickerService service.
// All implementations must embed UnimplementedTickerServiceServer
// for forward compatibility.
type TickerServiceServer interface {
	StreamTicker(*TickerRequest, grpc.ServerStreamingServer[TickerUpdate]) error
	mustEmbedUnimplementedTickerServiceServer()
}

// UnimplementedTickerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTickerServiceServer struct{}

func (UnimplementedTickerServiceServer) StreamTicker(*TickerRequest, grpc.ServerStreamingServer[TickerUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTicker not implemented")
}
func (UnimplementedTickerServiceServer) mustEmbedUnimplementedTickerServiceServer() {}
func (UnimplementedTickerServiceServer) testEmbeddedByValue()                       {}

// UnsafeTickerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TickerServiceServer will
// result in compilation errors.
type UnsafeTickerServiceServer interface {
	mustEmbedUnimplementedTickerServiceServer()
}

func RegisterTickerServiceServer(s grpc.ServiceRegistrar, srv TickerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTickerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TickerService_ServiceDesc, srv)
}

func _TickerService_StreamTicker_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TickerRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TickerServiceServer).StreamTicker(m, &grpc.GenericServerStream[TickerRequest, TickerUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TickerService_StreamTickerServer = grpc.ServerStreamingServer[TickerUpdate]

// TickerService_ServiceDesc is the grpc.ServiceDesc for TickerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TickerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ticker.TickerService",
	HandlerType: (*TickerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTicker",
			Handler:       _TickerService_StreamTicker_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ticker.proto",
}
